reto4Django/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin', admin.site.urls),
    url(r'^', include("web.urls", namespace="web")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns= [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^nosotros/', TemplateView.as_view(template_name='nosotros.html'), name='nosotros'),
]

web/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.

class CatBanners(models.Model):
    title = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.title

class Banners(models.Model):
    categoria = models.ForeignKey(CatBanners, on_delete=models.CASCADE)
    title = models.CharField(max_length=30, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    imagen = models.FileField(upload_to='banners', null=True, blank=True)

    def __str__(self):
        return self.title

class CatCustom(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.title

class Custom(models.Model):
    categoria = models.ForeignKey(CatCustom, on_delete=models.CASCADE)
    title = models.CharField(max_length=255, null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    imagen = models.FileField(upload_to='customs', null=True, blank=True)


    def __str__(self):
        return self.title

web/views.py
from django.http import HttpResponse
from django.shortcuts import render

templates/footer.html
{% load static %}
{% load customs %}

{% customs "footer" as section %}
<footer class="background_gray">
  <div class="container">
    {% for custom in section %}
      {{ custom.content | safe }}
    {% endfor %}
  </div>
</footer>

<!-- Js-->
<script src="{% static "/jquery/jquery.min.js" %}"></script>
<script src="{% static "/js/template.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>

templates/head.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="django v1.0">
    <meta name="author" content="Juan Camilo">

    <title>{% block title %}Reto Django v1.0{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static  "css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "css/main.min.css" %}" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" href="{% static "images/favicon.ico" %}"/>
</head>

templates/header.html
{% load static %}

<header>
  <nav class="navbar menuweb navbar-static-top navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><img class="img-responsive" src="{% static "images/logouseit.png" %}" alt="logouseit"></a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="" class="text-uppercase text_bold">Soluciones</a></li>
          <li><a href="" class="text-uppercase text_bold">Miestiloweb</a></li>
          <li><a href="{% url 'web:nosotros' %}" class="text-uppercase text_bold">Nosotros</a></li>
          <li><a href="" class="text-uppercase text_bold">Contacto</a></li>
        </ul>
      </div>
    </div>
  </nav>
</header>

templates/index.html
{% extends "web/base.html" %}
{% load customs %}

{% block content %}

{% banners "home" as banners %}
<section>
  <div id="banner">
  {% for banner in banners %}
    <img src="{{ banner.imagen }}" alt="{{ banner.title }}" class="img-responsive">
    <div class="carousel-caption">
      {{ banner.description | safe }}
    </div>
  {% endfor %}
  </div>
</section>

{% customs "tecnology" as tecnology %}
<section id="tecnology">
  <ul class="container">
    {% for custom in tecnology %}
      <li>
        <img src="{{ custom.imagen }}" alt="{{ custom.title }}">
      </li>
    {% endfor %}
  </ul>
</section>

{% customs "medida" as medida %}
<section id="medida" class="section">
  <div class="container">
    {% for custom in medida %}
      {{ custom.content | safe }}
      <img src="{{ custom.imagen }}" alt="{{ custom.title }}" class="img-responsive">
    {% endfor %}
  </div>
</section>

{% customs "section1" as section %}
<section id="section" class="section background_gray_light">
  <div class="container">
    {% for custom in section %}
      <div class="col-xs-12 col-sm-6">
          {{ custom.content | safe }}
      </div>
      <div class="col-xs-12 col-sm-6">
        <img src="{{ custom.imagen }}" alt="{{ custom.title }}" class="img_web img-responsive">
      </div>
    {% endfor %}
  </div>
</section>

{% customs "section2" as section %}
<section id="section" class="section background_gray">
  <div class="container">
    {% for custom in section %}
      <div class="col-xs-12 col-sm-6 pull-right">
          {{ custom.content | safe }}
      </div>
      <div class="col-xs-12 col-sm-6">
        <img src="{{ custom.imagen }}" alt="{{ custom.title }}" class="img_web img-responsive">
      </div>
    {% endfor %}
  </div>
</section>

{% customs "section3" as section %}
<section id="section" class="section background_gray_light">
  <div class="container">
    {% for custom in section %}
      <div class="col-xs-12 col-sm-6">
          {{ custom.content | safe }}
      </div>
      <div class="col-xs-12 col-sm-6">
        <img src="{{ custom.imagen }}" alt="{{ custom.title }}" class="img_web img-responsive">
      </div>
    {% endfor %}
  </div>
</section>

{% customs "exito" as section %}
<section class="background_gray">
  <div id="exito" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      {% for custom in section %}
      <li data-target="#exito" data-slide-to="{{forloop.counter0}}" class="{% if forloop.first %} active{% endif %}"></li>
      {% endfor %}
    </ol>
    <div class="container">
      <div class="carousel-inner">
        {% for custom in section %}
        <div class="item{% if forloop.first %} active{% endif %}">
          <h4 class="size_30">Caso de éxito: <span class="text_green">{{ custom.title | safe }}</span></h4>
          <div class="row">
            <div class="col-xs-12 col-md-6">
              <div class="carousel-caption text-left">
                {{ custom.content | safe }}
              </div>
            </div>
            <div class="col-xs-12 col-md-5 col-md-offset-1">
                <img src="{{ custom.imagen }}" alt="{{ custom.title }}" class="img-responsive">
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>

{% customs "logos" as section %}
<section id="logos">
  <div class="container">
    <ul>
      {% for custom in section %}
      <li><img src="{{ custom.imagen }}" alt="{{ custom.title }}" class="img-responsive"></li>
      {% endfor %}
    </ul>
  </div>
</section>

{% customs "testimonio" as section %}
<section id="testimonio" class="background_gray">
  <div id="carousel-example-generic3" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      {% for custom in section %}
        <li data-target="#carousel-example-generic3" data-slide-to="{{forloop.counter0}}" class="{% if forloop.first %} active{% endif %}"></li>
      {% endfor %}
    </ol>
    <div class="container">
      <div class="carousel-inner" role="listbox">
        {% for custom in section %}
        <div class="item {% if forloop.first %} active{% endif %}">
          <div class="media">
            <div class="col-xs-12 col-sm-1">
              <img src="customs/left.png" alt="left" class="img-responsive">
            </div>
            <div class="col-xs-12 col-sm-2">
              <div class="media-left">
                <a href="#">
                    <img src="{{ custom.imagen }}" alt="{{ custom.title }}" class="img-responsive">
                </a>
              </div>
            </div>
            <div class="col-xs-12 col-xs-offset-0 col-sm-6 col-sm-offset-1">
              <div class="media-body">
                  {{ custom.content | safe }}
              </div>
            </div>
            <div class="col-xs-12 col-sm-1">
              <img src="customs/right.png" alt="right" class="img-responsive" style="margin-top: 250%;">
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>

{% customs "frontend" as section %}
<section id="frontend">
  <div class="container text-center">
    {% for custom in section %}
      <img src="{{ custom.imagen }}" alt="{{ custom.title }}" class="img-responsive">
      {{ custom.content | safe }}
    {% endfor %}
  </div>
</section>

{% customs "lorem" as section %}
<section id="lorem" class="background_gray">
  <div class="container">
    <div class="row">
      <h2 class="size_30 text_white text-center">Lorem ipsum dolor sit amet</h2>
      <hr class="hr_title">
      {% for custom in section %}
      <div class="col col-xs-12 col-sm-6 col-sm-offset-0 col-md-3 col-md-offset-1">
        <img src="{{ custom.imagen }}" alt="{{ custom.title }}" class="img-responsive">
        {{ custom.content | safe }}
      </div>
      {% endfor %}
    </div>
  </div>
</section>

{% customs "proceso" as section %}
<section id="proceso" class="background_gray_light">
  <div class="container">
    <div class="row">
      {% for custom in section %}
          {% if custom.section|length > 0 %}
            <img src="{{ custom.imagen }}" alt="{{ custom.title }}" class="img-responsive">
          {% endif %}
        {{ custom.content | safe }}
      {% endfor %}
    </div>
  </div>
</section>

<section id="recientes">
  <div class="container">
    <h2 class="font_400">Reciente en miestiloweb</h2>
  </div>
</section>

{% customs "play" as section %}
<section id="play" class="background_gray_light">
  <div class="container">
    {% for custom in section %}
      {{ custom.content | safe }}
    {% endfor %}
  </div>
</section>

{% customs "contactanos" as section %}
<section id="contactanos" class="background_white">
  <div class="container">
    {% for custom in section %}
      {{ custom.content | safe }}
    {% endfor %}
  </div>
</section>

<!--http://miestiloweb.com/?format=feed&type=rss-->

{% endblock %}

templates/nosotros.html
{% extends "web/base.html" %}
{% load static %}

{% load customs %}


  {% block content %}

{% banners "banner_interna" as banners %}
<section id="banner_nosotros" class="text-center">
  {% for banner in banners %}
  <img src="{{ banner.imagen.url }}" alt="{{ banner.title }}" class="img-responsive">
  <div class="caption container text-center">
    {{ banner.description | safe }}
  </div>
  {% endfor %}
</section>

{% customs "content_nosotros1" as section %}
<section id="content_nosotros" class="text-center">
  <div class="container">
    {% for custom in section %}
    <div class="col-xs-12 co-sm-12">
      <img src="{{ custom.imagen.url }}" alt="{{ custom.title }}">
    </div>
    <div class="descripcion_nosotros col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2">
      {{ custom.content | safe }}
    </div>
    {% endfor %}
  </div>
</section>

{% customs "content_nosotros2" as section %}
<section id="content_nosotros" class="text-center">
  <div class="container">
    <div class="row">
      {% for custom in section %}
        {% for i in 16|times %}
          <div class="col-xs-12 col-sm-6 col-md-3">
            <div class="thumbnail">
              <img src="{{ custom.imagen.url }}" alt="{{ custom.title }}">
              <div class="caption">
                {{ custom.content | safe }}
              </div>
            </div>
          </div>
        {% endfor %}
      {% endfor %}
    </div>
  </div>
</div>
</section>

{% customs "frontend_nosotros" as section %}
<section id="frontend_nosotros" class="text-center">
  <div class="container content">
    {% for custom in section %}
      <img src="{{ custom.imagen.url }}" alt="{{ custom.title }}">
      {{ custom.content | safe }}
    {% endfor %}
  </div>
</section>

{% customs "trabajamos" as section %}
<section id="trabajamos" class="text-center">
  <div class="container content">
    {% for custom in section %}
      <h4 class="text_bold">{{ custom.title }}</h4>
      <hr>
      {{ custom.content | safe }}
      <img src="{{ custom.imagen.url }}" alt="{{ custom.title }}" class="aro">
    {% endfor %}
  </div>
  {% customs "trabajamos2" as section %}
  <div class="content_boton">
    {% for custom in section %}
      <img src="{{ custom.imagen.url }}" alt="{{ custom.title }}" class="teamuseit">
      {{ custom.content | safe }}
    {% endfor %}
  </div>
</section>

{% endblock %}

templates/web/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  {% include "head.html" %}

<body>
  {% include "header.html" %}

  {% block content %}
  {% endblock %}

  {% include "footer.html" %}
</body>
</html>